{
 "title": "PV",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"batt_soc\" or\r\n    r._field == \"pv_pwr\" or\r\n    r._field == \"pv_charge_pwr\" or\r\n    r._field == \"util_pwr\" or\r\n    r._field == \"inv_pwr\" or\r\n    r._field == \"bypass_pwr\"\r\n  )"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"batt_soc\" or\r\n    r._field == \"pv_pwr\" or\r\n    r._field == \"pv_charge_pwr\" or\r\n    r._field == \"util_pwr\" or\r\n    r._field == \"inv_pwr\" or\r\n    r._field == \"bypass_pwr\"\r\n  )"
    }
   ]
  },
  {
   "title": "DC Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"pv_volt\" or\r\n    r._field == \"pv_charge_volt\" or\r\n    r._field == \"util_charge_volt\" or\r\n    r._field == \"batt_volt\"\r\n  )"
    }
   ]
  },
  {
   "title": "DC Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"util_charge_cur\" or\r\n    r._field == \"pv_cur\" or\r\n    r._field == \"pv_charge_cur\"\r\n  )"
    }
   ]
  },
  {
   "title": "AC Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"bypass_volt\" or\r\n    r._field == \"util_volt\" or\r\n    r._field == \"inv_volt\"\r\n  )"
    }
   ]
  },
  {
   "title": "AC Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"inv_cur\" or\r\n    r._field == \"bypass_cur\"\r\n  )"
    }
   ]
  },
  {
   "title": "MPP Tracker",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "volt = from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"pv_volt\"\r\n  )\r\n\r\npwr = from(bucket: \"solardata\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"pv_pwr\"\r\n  )\r\n\r\njoin(\r\n    tables: {pwr, volt},\r\n    on: [\"_time\", \"_stop\", \"_start\", \"inverter\"],\r\n)"
    }
   ]
  }
 ]
}