{
 "title": "Energy",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "energy_price", "label": "Energy Price", "query": "0.25" },
   {
    "name": "pv_energy",
    "label": "PV Energy",
    "query": "from(bucket: \"solardata\")\r\n  |> range(start: 2022-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"pv_pwr\"\r\n  )\r\n  |> integral(unit: 1h)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001}))"
   },
   {
    "name": "utility_energy",
    "label": "Utility Energy",
    "query": "from(bucket: \"solardata\")\r\n  |> range(start: 2022-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"util_pwr\"\r\n  )\r\n  |> integral(unit: 1h)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001}))"
   },
   {
    "name": "bypass_energy",
    "label": "Bypass Energy",
    "query": "from(bucket: \"solardata\")\r\n  |> range(start: 2022-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"bypass_pwr\"\r\n  )\r\n  |> integral(unit: 1h)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001}))"
   },
   {
    "name": "inv_energy",
    "label": "Inverter Energy",
    "query": "from(bucket: \"solardata\")\r\n  |> range(start: 2022-01-01T00:00:00Z)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"solards\" and\r\n    r._field == \"inv_pwr\"\r\n  )\r\n  |> integral(unit: 1h)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001}))"
   }
  ]
 },
 "panels": [
  {
   "title": "PV Energy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "${pv_energy}", "type": "math" },
    {
     "expression": "${pv_energy} *  ${energy_price}",
     "type": "math"
    }
   ]
  },
  {
   "title": "Utility Energy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "${utility_energy}", "type": "math" },
    {
     "expression": "${utility_energy} * ${energy_price}",
     "type": "math"
    }
   ]
  },
  {
   "title": "Server Energy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "${bypass_energy}", "type": "math" },
    {
     "expression": "${inv_energy} - ${bypass_energy}",
     "type": "math"
    },
    {
     "expression": "(${bypass_energy} - ${utility_energy}) * ${energy_price}",
     "type": "math"
    }
   ]
  },
  {
   "title": "Energy Mix",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "${pv_energy}", "type": "math" },
    { "expression": "${utility_energy}", "type": "math" }
   ]
  }
 ]
}